import { IImpuchip } from "@/types/Types";
import { useFetchCompani } from "../services/Compani";

export const inputstabla: IImpuchip[] = [
  {
    id: 1,
    tipo: "date",
    name: "fecha",
    label: "Fecha instalacion:",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 2,
    tipo: "TIME",
    name: "hours",
    label: "Hora:",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 3,
    tipo: "autocomplete",
    name: "company",
    label: "Empresa:",
    valor: [""],
    shrink: false,
  },
  {
    id: 4,
    tipo: "selected",
    name: "installationtype",
    label: "Tipo:",
    valor: ["DOMICILIO", "EMPRESA"],
    shrink: false,
  },
  {
    id: 5,
    tipo: "text",
    name: "address",
    label: "Direccion",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 18,
    tipo: "selected",
    name: "installer",
    label: "Instalador:",
    valor: ["ISAAC", "JONATHAN"],
    shrink: false,
  },
  {
    id: 6,
    tipo: "text",
    name: "vehiclename",
    label: "Vehiculo",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 7,
    tipo: "text",
    name: "patent",
    label: "Patente:",
    valor: [""],
    shrink: false,
  },
  {
    id: 8,
    tipo: "text",
    name: "note",
    label: "Notas:",
    valor: ["0"],
    shrink: true,
  },
  {
    id: 9,
    tipo: "autocomplete",
    name: "name",
    label: "Nombre:",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 10,
    tipo: "text",
    name: "email",
    label: "Correo:",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 11,
    tipo: "number",
    name: "fone",
    label: "Telefono:",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 12,
    tipo: "autocomplete",
    name: "label",
    label: "Dispositivo:",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 13,
    tipo: "money",
    name: "cost",
    label: "Costo:",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 14,
    tipo: "money",
    name: "value",
    label: "Valor :",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 15,
    tipo: "number",
    name: "imeigps",
    label: "ImeiGPS:",
    valor: ["0"],
    shrink: false,
  },
  {
    id: 16,
    tipo: "selected",
    name: "tipochip",
    label: "Tipo Chip:",
    valor: ["ENTEL", "WOM", "VIRGIN"],
    shrink: false,
  },
  {
    id: 17,
    tipo: "number",
    name: "numerochip",
    label: "Numero Chip",
    valor: ["0"],
    shrink: false,
  }
];
