export const columns = [
    { label: "Empresa", data: "company" },
    { label: "Fecha", data: "fecha" },
    { label: "Hora", data: "hours" },
    { label: "Cliente", data: "client" },
    { label: "Pantene", data: "patent" },
    { label: "Vehiculo", data: "vehiclename" },
    { label: "Tipo", data: "installationtype" },
    { label: "Direccion", data: "address" },
    { label: "Comuna", data: "commune" },
    { label: "Tipo pago", data: "state" },
    { label: "DI", data: "di" },
    { label: "Notas", data: "note" },
    { label: "Acciones", data: "actions" },
  ];
